[package]
name = "AI-Recommendations"
version = "1.0.0"
edition = "2021"


[dependencies]
tensorflow = "0.21.0"
warp = "0.3"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"